services:
  # Web service
  - type: web
    name: student-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: mysql://uvbwhdgisy4zr3ns:BGliwNiIfmGN9207aY0X@bcmkcmi6ytav8aqcjj1u-mysql.services.clever-cloud.com:3306/bcmkcmi6ytav8aqcjj1u
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false